SOCKS_VERSION = 5
RECEIVE_VERSION_LENGTH = 1
RECEIVE_HEADER_LENGTH = 2

# response
RESPONSE_FOR_AUTH = 2
RESPONSE_FOR_AUTH_VERSION = 1
AUTH_SUCCESS = 0
AUTH_FAIL = 1

# request
REQUEST_WITH_AUTH = 2
ATYP_IP = 1
ATYP_DOMAIN = 3
